[package]
name = "simp-cal"
version = "0.3.6"
edition = "2024"
description = "Converts text calculations into expressions then can calculate them"
license-file = "LICENSE"
repository = "https://github.com/Blockitifluy/simp-cal"
keywords = ["calculator"]
categories = ["calculator"]

[features]
f64 = []

[dependencies]
simp-cal-derive = { path = "simp-cal-derive" }

[profile.release]
strip = true
opt-level = "z"
lto = true
