[package]
name = "kalk"
version = "0.3.6"
edition = "2024"
description = "Converts text calculations into expressions then can calculate them"
license-file = "LICENSE"
repository = "https://github.com/Blockitifluy/kalk"
keywords = ["calculator"]
categories = ["calculator"]

[features]
f64 = []

[dependencies]
kalk-derive = { path = "kalk-derive" }

[profile.release]
strip = true
opt-level = "z"
lto = true
